### ISSUE TITLE
installation script failing

### ISSUE THREAD

**Issue by Nikolajal** [alidock/alidock#160]
nikolajal@Nicolas-MacBook-Pro alidock % bash <(curl -fsSL https://raw.githubusercontent.com/alidock/alidock/master/alidock-installer.sh)
Checking if your Docker installation works
Creating an environment for alidock using Python 3.8.2 (python3) and virtualenv 16.2.0
+ python3 pypa-virtualenv-d5fed23/virtualenv.py /Users/nikolajal/.virtualenvs/alidock
Using base prefix '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8'
New python executable in /Users/nikolajal/.virtualenvs/alidock/bin/python3
Also creating executable in /Users/nikolajal/.virtualenvs/alidock/bin/python
Traceback (most recent call last):
  File "pypa-virtualenv-d5fed23/virtualenv.py", line 2438, in <module>
    main()
  File "pypa-virtualenv-d5fed23/virtualenv.py", line 758, in main
    create_environment(
  File "pypa-virtualenv-d5fed23/virtualenv.py", line 1013, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "pypa-virtualenv-d5fed23/virtualenv.py", line 1428, in install_python
    shutil.copy(original_python, py_executable)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 240, in copyfile
    if _samefile(src, dst):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 217, in _samefile
    return os.path.samefile(src, dst)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/genericpath.py", line 100, in samefile
    s1 = os.stat(f1)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Old alidock installation was restored

**Comment by mconcas** [comment]
I am working on a fix for this issue, try with the python 3.7 installed via brew, it will work.

**Comment by mconcas** [comment]
Hi @Nikolajal,

In case you are still having issues with alidock I suggest you to reinstall it form the master version of this repo. You can do it by typing:

`bash <(curl -fsSL https://raw.githubusercontent.com/alidock/alidock/master/alidock-installer.sh) git`

Let me know, if it works I'll publish an updated release.

Cheers

**Comment by Nikolajal** [comment]
Thank you very much, everything seems to work just fine
