### ISSUE TITLE
Alidock installing  on Mac OS fail (ModuleNotFoundError: No module named 'six')

### ISSUE THREAD

**Issue by boonying04** [alidock/alidock#189]
Hi,
I got problem while installing alidock on Mac OS Big Sur v.11.4 
after this command : bash <(curl -fsSL https://raw.githubusercontent.com/alidock/alidock/master/alidock-installer.sh)

I got the error message say  "ModuleNotFoundError: No module named 'six'"
when I try to use alidock it giving the same error message.

full message bellow here:
Checking if your Docker installation works
Creating an environment for alidock using Python 3.9.5 (python3)
Installing alidock under /Users/(user_name)/.virtualenvs/alidock
Traceback (most recent call last):
  File "/Users/(user_name)/.virtualenvs/alidock/bin/alidock", line 5, in <module>
    from alidock import entrypoint
  File "/Users/(user_name)/.virtualenvs/alidock/lib/python3.9/site-packages/alidock/__init__.py", line 18, in <module>
    import docker
  File "/Users/(user_name)/.virtualenvs/alidock/lib/python3.9/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/Users/(user_name)/.virtualenvs/alidock/lib/python3.9/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/Users/(user_name)/.virtualenvs/alidock/lib/python3.9/site-packages/docker/api/client.py", line 10, in <module>
    from .. import auth
  File "/Users/(user_name)/.virtualenvs/alidock/lib/python3.9/site-packages/docker/auth.py", line 5, in <module>
    import six
ModuleNotFoundError: No module named 'six'
Installed: 
You can use alidock by simply typing:
    alidock

Any advice would be appreciated.
Thank you.

**Comment by Nikolajal** [comment]
I managed to solve with:
>source /Users/your_user_name/.virtualenvs/alidock/bin/activate
>pip install six
>deactivate
>alidock

**Comment by boonying04** [comment]
It seems to be working now, thank you for your advice it very helpful.
