### ISSUE TITLE
Mac: cannot run alidock after upgrade of docker and xcode

### ISSUE THREAD

**Issue by raquishp** [alidock/alidock#193]
Dear experts,

I'm having trouble building AliPhysics after upgrades of docker and xcode. After the upgrades, I was not able to compile AliPhysics anymore, and the error was due to libperl, so I reinstalled it, and it still didn't work, so I removed everything and reinstalled from scratch. Now I'm trying to install again alidock with the tutorial, but I get the following error:

````
$%bash <(curl -fsSL https://raw.githubusercontent.com/alidock/alidock/master/alidock-installer.sh))



Checking if your Docker installation works

Creating an environment for alidock using Python 3.9.6 (python3)

Installing alidock under /Users/raquelquishpe/.virtualenvs/alidock

Traceback (most recent call last):

  File "/Users/raquelquishpe/.virtualenvs/alidock/bin/alidock", line 5, in <module>

    from alidock import entrypoint

  File "/Users/raquelquishpe/.virtualenvs/alidock/lib/python3.9/site-packages/alidock/__init__.py", line 18, in <module>

    import docker

  File "/Users/raquelquishpe/.virtualenvs/alidock/lib/python3.9/site-packages/docker/__init__.py", line 2, in <module>

    from .api import APIClient

  File "/Users/raquelquishpe/.virtualenvs/alidock/lib/python3.9/site-packages/docker/api/__init__.py", line 2, in <module>

    from .client import APIClient

  File "/Users/raquelquishpe/.virtualenvs/alidock/lib/python3.9/site-packages/docker/api/client.py", line 10, in <module>

    from .. import auth

  File "/Users/raquelquishpe/.virtualenvs/alidock/lib/python3.9/site-packages/docker/auth.py", line 5, in <module>

    import six

ModuleNotFoundError: No module named 'six'

Installed: 

You can use alidock by simply typing:

    alidock
````

when running "alidock" I get:
````
Traceback (most recent call last):

  File "/Users/raquelquishpe/.virtualenvs/alidock/bin/alidock", line 5, in <module>

    from alidock import entrypoint

  File "/Users/raquelquishpe/.virtualenvs/alidock/lib/python3.9/site-packages/alidock/__init__.py", line 18, in <module>

    import docker

  File "/Users/raquelquishpe/.virtualenvs/alidock/lib/python3.9/site-packages/docker/__init__.py", line 2, in <module>

    from .api import APIClient

  File "/Users/raquelquishpe/.virtualenvs/alidock/lib/python3.9/site-packages/docker/api/__init__.py", line 2, in <module>

    from .client import APIClient

  File "/Users/raquelquishpe/.virtualenvs/alidock/lib/python3.9/site-packages/docker/api/client.py", line 10, in <module>

    from .. import auth

  File "/Users/raquelquishpe/.virtualenvs/alidock/lib/python3.9/site-packages/docker/auth.py", line 5, in <module>

    import six

ModuleNotFoundError: No module named 'six'

Saving session...

...saving history...truncating history files...

...completed.
````

but I have already installed "six"

`Requirement already satisfied: six in /usr/local/lib/python3.9/site-packages (1.16.0)`

do you probably know how I can solve this?
Thanks

**Comment by mconcas** [comment]
Hello @raquishp : https://github.com/alidock/alidock/issues/189 presents a solution.

Let me know if it works.

**Comment by raquishp** [comment]
> Hello @raquishp : #189 presents a solution.
> 
> Let me know if it works.

Hi @mconcas, thanks for the link, it solved that part. However, now I have another issue. When testing locally my task, I used to compile it by running:

````
cd /persist/sw/BUILD/AliPhysics-latest/AliPhysics
make -j 4 install
````

however, when running `make -j 4 install` I get the following problem:

````
[AliPhysics/latest-master-user-next-root6] /persist/sw/BUILD/AliPhysics-latest/AliPhysics $> make -j 4 install
make: *** No rule to make target `install'.  Stop.
````

do you know why this is happening? or do you have an alternative way to compile my change to the task without needing to fully rebuild AliPhysics every time?

**Comment by mconcas** [comment]
`make install -j4` ?
