### ISSUE TITLE
Add possibility to publish container port on host

### ISSUE THREAD

**Issue by mconcas** [alidock/alidock#40]
It will become natural to have some people wanting to use jupyter notebooks or similia.
This can't be done, afaik, at the moment.

It would be a good enhancement.

**Comment by dberzano** [comment]
It would be essential by Friday, since Markus' tutorial is based... on Jupyter 🙂

**Comment by dberzano** [comment]
On Jupyter notebooks I have opened an issue to ROOT, see [ROOT-9829](https://sft.its.cern.ch/jira/browse/ROOT-9829). See also kaczmarj/neurodocker#82.

The ROOT issue describes our workaround for making it work. Once it does, we still need to forward the port, _somehow_. We could even use SSH for that, but I'd prefer to use Docker's native capabilities.

For SSH, we have Docker mapping 22 to a random port. Ideally we should do the same here, but we need a way to retrieve that port and to configure it.

Ideas are welcome, this is not urgent.

**Comment by zsaldic** [comment]
Dear @dberzano,  

I am interested in using jupyter notebook inside alidock, but none of the suggested solutions worked me. Here is a summary of what I tried to do:

Inside an `alidock` container  I enter an alienviroment as usual.
`$> jupyter notebook` returns the traceback 

```
Traceback (most recent call last):
  File "/persist/sw/slc7_x86-64/Python-modules/1.0-67/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/persist/sw/slc7_x86-64/Python-modules/1.0-67/lib/python/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/persist/sw/slc7_x86-64/Python-modules/1.0-67/lib/python/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</persist/sw/slc7_x86-64/Python-modules/1.0-67/lib/python/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/persist/sw/slc7_x86-64/Python-modules/1.0-67/lib/python/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/persist/sw/slc7_x86-64/Python-modules/1.0-67/lib/python/site-packages/notebook/notebookapp.py", line 1630, in initialize
    self.init_webapp()
  File "/persist/sw/slc7_x86-64/Python-modules/1.0-67/lib/python/site-packages/notebook/notebookapp.py", line 1407, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/persist/sw/slc7_x86-64/Python-modules/1.0-67/lib/python/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/persist/sw/slc7_x86-64/Python-modules/1.0-67/lib/python/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
```

Whereas;

`$> jupyter notebook --ip=0.0.0` 

returns

```
[I 14:22:01.167 NotebookApp] Serving notebooks from local directory: /home/alidock
[I 14:22:01.167 NotebookApp] The Jupyter Notebook is running at:
[I 14:22:01.167 NotebookApp] http://(alidock-501 or 127.0.0.1):8888/?token=3f0ca61f4c5ded6aebcafc6b34b91ac0f5344cb95cdbdf8e
[I 14:22:01.167 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:22:01.182 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/alidock/.local/share/jupyter/runtime/nbserver-10876-open.html
    Or copy and paste one of these URLs:
        http://(alidock-501 or 127.0.0.1):8888/?
token=3f0ca61f4c5ded6aebcafc6b34b91ac0f5344cb95cdbdf8e
xdg-open: no method available for opening 'file:///home/alidock/.local/share/jupyter/runtime/nbserver-10876-open.html'
```

X11 opens up, but no sign of a jupyter notebook in a browser. Also the above suggested links do not work. Any suggestions to how to make jupyter notebook work inside an alidock enviroment?

Best Regards,
Zlatko

**Comment by mconcas** [comment]
See #146
